### PR TITLE
C# Favicon to Byte Array

### PR DESCRIPTION
**Pull request by jrdiver**
## Proposed Changes
C# add base 64 => Byte array property

### CODE REVIEW

**Comment by jrdiver** [comment]
As discussed in 126.  Decode it option added

**Comment by ldilley** [comment]
Greetings and thanks again for knocking this out, @jrdiver. I also apologize for the delay in reviewing this PR.

While testing against "us.mineplex.com" (which does have a favicon), the following line of code yields false and assigns `null`:

```cs
public byte[] FaviconBytes => string.IsNullOrWhiteSpace(Favicon) && Favicon.Contains("base64,") ? Convert.FromBase64String(Favicon.Substring(Favicon.IndexOf(",") + 1)) : null;
```

Adding the `!` (logical not) operator in front of `string.IsNullOrWhiteSpace(Favicon)` should resolve the issue.

**Comment by jrdiver** [comment]
That was meant to be there... Not sure how I missed that in my check before I submitted it. I'll correct it later tonight.

**Comment by jrdiver** [comment]
Should be good now.

**Review by ldilley — APPROVED** [review]

**Pull request merged**
