### PR TITLE
feats(JS): Typedefs + promise support

### PR DESCRIPTION
**Pull request by kolyaventuri**
## Proposed Changes
- Adds type definitions
- Adds changelog
- (breaking): Adds `init` as an async method, moves callback to `initSync`
- (breaking): Migrates discrete arguments to be a single `{address: string, port: number, timeout?: number}` object
- (breaking): Removes the `process.exit()` line which would kill parents apps if used as a library (ref: #10)

### CODE REVIEW

**Comment by kolyaventuri** [comment]
Went back and forth on if this should be 2+ PRs... Alternative way to break this apart would be:

- Add typedef
- Add promisified version of `init` and update typedefs
- (maybe, or as above) Object notation to allow default 25565 port

**Review by ldilley — COMMENTED** [review]
Thank you very much for modernizing the JavaScript code, @kolyaventuri. I hope you do not mind some of the changes I've committed to this PR. I did revert to using seconds for the timeout to maintain parity with the other language implementations of MineStat.

I've successfully tested `initSync()`. The only issue seems to be with the async method. I'm using the following:
```javascript
  const ms = require('./minestat');
  try {
    const result = await ms.init({address: 'minecraft.frag.land'});
    // ...
  }  
```

However, I am getting the error below:
```
/home/ldilley/projects/tmp/minestat/JavaScript/example.js:4
    const result = await ms.init({address: 'minecraft.frag.land'});
                   ^^^^^

SyntaxError: await is only valid in async functions and the top level bodies of modules
    at internalCompileFunction (node:internal/vm:74:18)
    at wrapSafe (node:internal/modules/cjs/loader:1141:20)
    at Module._compile (node:internal/modules/cjs/loader:1182:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.13.0
```

**Comment by kolyaventuri** [comment]
> Thank you very much for modernizing the JavaScript code, @kolyaventuri. I hope you do not mind some of the changes I've committed to this PR. I did revert to using seconds for the timeout to maintain parity with the other language implementations of MineStat.
> 
> I've successfully tested `initSync()`. The only issue seems to be with the async method. I'm using the following:
> 
> ```js
>   const ms = require('./minestat');
>   try {
>     const result = await ms.init({address: 'minecraft.frag.land'});
>     // ...
>   }  
> ```
> 
> However, I am getting the error below:
> 
> ```
> /home/ldilley/projects/tmp/minestat/JavaScript/example.js:4
>     const result = await ms.init({address: 'minecraft.frag.land'});
>                    ^^^^^
> 
> SyntaxError: await is only valid in async functions and the top level bodies of modules
>     at internalCompileFunction (node:internal/vm:74:18)
>     at wrapSafe (node:internal/modules/cjs/loader:1141:20)
>     at Module._compile (node:internal/modules/cjs/loader:1182:27)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
>     at Module.load (node:internal/modules/cjs/loader:1081:32)
>     at Module._load (node:internal/modules/cjs/loader:922:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
>     at node:internal/main/run_main_module:23:47
> 
> Node.js v18.13.0
> ```

Aaah I wonder if the top-level await is only valid in ESM modules... If you wrap it in an async IIFE it should work fine for the purposes of testing

i.e.

```typescript
const ms = require('./minestat');
(async () => {
  try {
    const result = await ms.init({address: 'minecraft.frag.land'});
    // ...
  }  catch {}
})();
```

**Comment by kolyaventuri** [comment]
Alternative testing method would be to create an `example-async.mjs` file with the following

```typescript
import ms from './minestat.js';

const result = await ms.init({address: 'minecraft.frag.land'});

console.log(result);
```

**Review by ldilley — APPROVED** [review]

**Comment by ldilley** [comment]
Thanks again, @kolyaventuri. Both of your async recommendations worked. Once the CodeQL checks complete, I'll pull the merge trigger on this PR and then ensure the npm module gets updated.

**Pull request merged**
