### PR TITLE
Nuget publish github action bugfix

### PR DESCRIPTION
**Pull request by Ajoro**
## Proposed Changes
The nuget publish github action https://github.com/FragLand/minestat/actions/runs/2853221059 fails because the `dotnet pack` command dosen't work, because their is no target named pack. My solution is to swap to a later .csproj format. When i did this change I noticed that the version of the created nupkg failed to change that is why I moved almost all assembly info to the .csproj file. Since comvisable can't be move to .csproj yet I kept the file. https://github.com/hvanbakel/CsprojToVs2017/issues/168

I don't know how this affects working in visual studio and building on older systems. But I think it would solve the problem? 
Im interested to see what other errors come up when the other actions are run!

### CODE REVIEW

**Comment by mindsolve** [comment]
@Ajoro: I think simly adding

```yml
before_build:
  - nuget restore CSharp\\MineStat.sln
```

to the appveyor.yml should fix the failing appveyor build.

**Comment by Ajoro** [comment]
@ldilley Could you try the publish powershell action next? Gallery version: 2.0.2 Latest version: 2.0.3 ?

**Comment by ldilley** [comment]
> @ldilley Could you try the publish powershell action next? Gallery version: 2.0.2 Latest version: 2.0.3 ?

I executed the action and the result appeared to be successful. However, the module was not actually updated to 2.0.3 at PowerShell Gallery.

**Comment by Ajoro** [comment]
Apparently the module needs a folder with the same name. https://github.com/PowerShell/PowerShellGetv2/issues/405
Let's see if this works.. :)

**Review by ldilley — APPROVED** [review]

**Comment by ldilley** [comment]
The PowerShell publish action is working now, @Ajoro. Thank you for fixing it.

**Pull request merged**
