### PR TITLE
Feature: [C#] Add full SLP protocol support

### PR DESCRIPTION
**Pull request by mindsolve**
As this is the first time writing C#, I would love some constructive feedback!
The general layout is based on the PHP, Python and Java implementations.

### Proposed Changes (C# specific)
- Added the `beta`, `extended legacy` and `json` SLP protocols
- Rewrote the `legacy` protocol implementation
- Added enums for protocol and connection status
- Added optional "force specific protocol" parameter
- Added dependency on `Newtonsoft.Json` for `json` SLP protocol [!]
- Bumped version to 2.0

### Proposed Changes (Documentation)
- Edited the example to use class variable accessors (not the deprecated getter methods)

### Proposed Changes (other)
- Added `.exe` and `.dll` files to `.gitignore` to ignore all binary executables, not only Example and Minestat files.

### CODE REVIEW

**Comment by mindsolve** [comment]
Dear @ldilley, from my perspective, this PR is now ready for review! :smile:

**Review by ldilley — COMMENTED** [review]
Were these 2 binaries (`Example.exe` and `MineStat.dll`) intended to be removed from the `.gitignore` file? It seems that they still get built. We generally do not want to commit binary files to git (https://robinwinslow.uk/dont-ever-commit-binary-files-to-git).

**Comment by mindsolve** [comment]
> Were these 2 binaries (`Example.exe` and `MineStat.dll`) intended to be removed from the `.gitignore` file?

No, I added `*.exe` and `*.dll` to the `.gitignore` file, as I had some more example files for testing and didn't want to accidentally commit them. As far as I could see, we never commit binaries.

**Comment by ldilley** [comment]
Related to issues #20, #21, and #22.

**Comment by ldilley** [comment]
This looks great, @mindsolve. Nicely done! The remaining issue is getting Mono support for `System.Runtime.Serialization.Json` and `System.Xml.Linq`.

**Comment by ldilley** [comment]
To fix the Travis CI Mono build, it looks like the following packages need to be installed prior to building the DLL:
* `libmono-system-xml-linq4.0-cil`
* `libmono-system-runtime-serialization4.0-cil`

Try modifying `.travis.yml` to contain the following in the `csharp` section near the top:
```yaml
  include:
    - language: csharp
      script:
        - sudo apt-get -y install libmono-system-xml-linq4.0-cil libmono-system-runtime-serialization4.0-cil
        - cd CSharp && mcs Example.cs MineStat/MineStat.cs
```

**Comment by mindsolve** [comment]
AFAIK, those two assemblies are included in the normal mono installation (`mono-complete`), but you must manually reference them (see https://www.mono-project.com/community/help/#can-not-compile-my-source).
What exactly do you mean then by "fixing the build"? The build was successful.

**Comment by ldilley** [comment]
I was still looking at the previous failed build (35.1). I see that you've since added "`-reference:System.Runtime.Serialization.dll -reference:System.Xml.Linq.dll`". We're all good to merge then.

**Review by ldilley — APPROVED** [review]

**Pull request merged**
