### PR TITLE
Update MineStat.java

### PR DESCRIPTION
**Pull request by Osiris-Team**
I think it makes more sense this way.

### CODE REVIEW

**Comment by mindsolve** [comment]
Dear @Osiris-Team,

A warm welcome to minestat & thank you for opening this PR!
Unfortunately, I see a few issues with your changes:

1. Your changes would break compatibility with older Minecraft versions (< 1.7), which we would like to continue to support.
  I understand the motive to try to use the best, current & most used protocol first, but older servers incorrectly try to parse the `json` (<1.7) SLP protocol and reject any further connection attempts for a few seconds, breaking the protocol detection. For more information see the comment you deleted and issue FragLand/minestat#70.
  The order of protocols tried is therefore important and was tested with all major Minecraft versions to correctly return data.
2. You completely removed the code for manual protocol selection (parameter `requestType`) by removing the switch statement. This parameter allows a user to force a specific protocol and disable the automatic protocol selection, e.g. if the remote server version is known to be >= 1.7.

As such, I would vote against merging your PR in its current state.

Best regards,
MindSolve

**Comment by Osiris-Team** [comment]
@mindsolve With the old method the version gets not detect properly, that's why I made the changes and thus could fix my issue. Now however the server's MOTDs are always null.

Any ideas?

**Comment by mindsolve** [comment]
@Osiris-Team: Interesting. The problem with the version detection being wrong is new to me, I would suggest opening a new issue with the specifics (with server version please) to be able to troubleshoot that properly.

Your new problem with the motd being empty could be related to issue #84, if the motd contains formatting (such as colors or bold/underlined, etc.). We are in the process of fixing that, but if you need a workaround _now_, you could revert to our version and force the protocol to be `extended_legacy` via the `requestType` (fourth) parameter.

Workaround example:
```java
MineStat ms = new MineStat("minecraft.frag.land", 25565, MineStat.DEFAULT_TIMEOUT, MineStat.Request.EXTENDED);
```

If you need any further assistance, open an issue or join the FragLang Discord server (https://discord.frag.land/) and ask your questions in the minestat channel :)

Best regards,
MindSolve

**Comment by mindsolve** [comment]
Dear @Osiris-Team,

I am going to close this PR now, as the issue is being resolved with another PR.

Thank you and best regards,
~MindSolve

**Pull request closed without merging**
